import io
import json
import uuid
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
import torchvision
from PIL import Image
from torchvision import transforms

from app.config import settings

NUM_CLASSES = 38
_TRANSFORM = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])


class OODException(Exception):
    """Raised when an image is geometrically far from all training-class centroids."""
    def __init__(self, score: float):
        self.score = score
        super().__init__(f"OOD score={score:.1f}")


def _build_model() -> nn.Module:
    model = torchvision.models.efficientnet_b0(weights=None)
    model.classifier[1] = nn.Linear(1280, NUM_CLASSES)
    return model


class PlantClassifier:
    def __init__(self):
        self._model: nn.Module | None = None
        self._class_names: dict[str, str] = {}
        self._metadata: dict[str, dict] = {}
        # OOD detection state — None means OOD check is disabled
        self._class_means: torch.Tensor | None = None
        self._precision: torch.Tensor | None = None
        self._ood_threshold: float = settings.ood_threshold

    def load(self):
        weights_path = Path(settings.model_weights_path)
        if not weights_path.exists():
            return

        self._model = _build_model()
        self._model.load_state_dict(
            torch.load(weights_path, map_location="cpu", weights_only=True)
        )
        self._model.eval()

        with open(weights_path.parent / "class_names.json") as f:
            self._class_names = json.load(f)

        with open(Path(__file__).parent / "disease_metadata.json") as f:
            self._metadata = json.load(f)

        # Load OOD stats if present (generated by ml/compute_ood_stats.py)
        means_path = weights_path.parent / "class_means.npy"
        prec_path = weights_path.parent / "precision_matrix.npy"
        if means_path.exists() and prec_path.exists():
            self._class_means = torch.tensor(np.load(means_path), dtype=torch.float32)
            self._precision = torch.tensor(np.load(prec_path), dtype=torch.float32)

    def is_loaded(self) -> bool:
        return self._model is not None

    def ood_enabled(self) -> bool:
        return self._class_means is not None

    def _mahalanobis_ood_score(self, features: torch.Tensor) -> float:
        """Minimum Mahalanobis distance from a feature vector to any class centroid.

        High score → likely OOD (not a plant leaf).
        Score = sqrt( min_c (f - μ_c)^T Σ^{-1} (f - μ_c) )
        """
        diffs = features.unsqueeze(0) - self._class_means  # [38, 1280]
        scores = torch.einsum("ci,ij,cj->c", diffs, self._precision, diffs).clamp(min=0)
        return float(scores.min().sqrt())

    def predict(self, image_bytes: bytes) -> dict:
        if not self._model:
            raise RuntimeError("Model not loaded")

        image = Image.open(io.BytesIO(image_bytes)).convert("RGB")
        tensor = _TRANSFORM(image).unsqueeze(0)

        with torch.no_grad():
            # Extract 1280-dim backbone features and classifier logits separately
            # so we can run the OOD check on the feature vector.
            features = torch.flatten(
                self._model.avgpool(self._model.features(tensor)), 1
            )  # [1, 1280]
            logits = self._model.classifier(features)
            probs = torch.softmax(logits, dim=1)
            confidence, idx = probs.max(dim=1)

        if self._class_means is not None:
            ood_score = self._mahalanobis_ood_score(features.squeeze(0))
            if ood_score > self._ood_threshold:
                raise OODException(ood_score)

        class_key = self._class_names[str(idx.item())]
        meta = self._metadata[class_key]

        return {
            "scan_id": str(uuid.uuid4()),
            "disease_name": meta["disease_name"],
            "is_healthy": meta["is_healthy"],
            "confidence": round(confidence.item(), 4),
            "severity": meta["severity"],
            "description": meta["description"],
            "treatments": meta["treatments"],
            "plant_type": meta["plant_type"],
            "created_at": datetime.now(timezone.utc).isoformat(),
        }


classifier = PlantClassifier()
